name: Test on PR

# On pull_request, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests

on:
  pull_request:

jobs:

  tests:
    name: Run Tests
    uses: ./.github/workflows/integrate.yaml
    secrets:
      charmcraft-credentials: "${{ secrets.CHARMCRAFT_CREDENTIALS }}"
